# Stage 1: Build React app using Node.js
FROM node:20-alpine AS build

WORKDIR /app

# Copy the package.json files
COPY package*.json ./

# Define the environment variable for React
ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL

# Install the dependencies and build the React app
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the React app using Nginx
FROM nginx:alpine

# Copy the build output from the previous stage into Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Copy the Nginx default config
COPY Nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose port 3000 for the React app (you will need to make sure your React app is listening on port 3000)
EXPOSE 3000

# Update Nginx config to listen on port 3000 instead of 80
CMD ["nginx", "-g", "daemon off;"]